### ISSUE TITLE
Package is installable in .NET Framework projects but doesn't work with .NET Framework projects

### ISSUE THREAD

**Issue by jslicer** [SteveDunn/Intellenum#126]
### Describe the bug

Creating a .NET Framework 4.8 project (for instance) and adding Intellenum as a NuGet package succeeds, but the functionality of Intellenum is unavailable.

### Steps to reproduce

1. Create a .NET Framework 4.8 Console App
2. Manage NuGet packages
3. Search for and install Intellenum
4. Installation succeeds
5. Intellenum functionality is unavailable to the project (the other partial classes are not generated).

### Expected behaviour

There should be a minimum requirement for which SDK the NuGet package is allowed to be installed into, and it is not .NET Framework (4.8 and prior), but rather .NET (formerly Core).

**Comment by SteveDunn** [comment]
Hi @jslicer - thanks for the report. I'll take a look at this shortly.

**Comment by SteveDunn** [comment]
Apologies for the delay. I've [documented this ](https://stevedunn.github.io/Intellenum/faq.html#what-versions-of-net-are-supported) in case other users have the same issue.
Please let me know if it doesn't work.
