### ISSUE TITLE
Allow one parameter to specify members for int based enums

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Intellenum#127]
### Describe the feature

Taken from this feature request: https://github.com/SteveDunn/Vogen/issues/562

Instances of ints should allow just one parameter to describe members; the values of which start at zero and increment, just like normal enums

**Comment by SteveDunn** [comment]
This has now been implemented on a branch and will be merged shortly.
The syntax is:
```c#
[Members("Standard, Gold, Platinum")]
public partial class CustomerType;
```

I tried to extend the feature to take names and values, e.g.
```c#
[Members(("Standard", 100), ("Gold", 200), ("Platinum", 300)]
```

... but there is a restriction on parameters in attributes as described here: https://github.com/dotnet/csharplang/discussions/1979

The new '[params collections](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/params-collections)' in C# 13 won't help either as it's not possible to use `IEnumerable<T>`

**Comment by arteny** [comment]
Hm, looks like it is implemented for int type only, when I asked it for string underlaying time.
Getting error 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	INTELLENUM027	The type 'ColorStyle' cannot have a Members attribute because it is not based on int
```

**Comment by SteveDunn** [comment]
Thanks @arteny - sorry about that, I'll take a look soon, hopefully within the next day or so.

**Comment by SteveDunn** [comment]
> Hm, looks like it is implemented for int type only, when I asked it for string underlaying type (https://github.com/SteveDunn/Vogen/issues/562).
> Getting error 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)	INTELLENUM027	The type 'ColorStyle' cannot have a Members attribute because it is not based on int
> ```
> 

This is now implemented and released.

**Comment by arteny** [comment]
> This is now implemented and released.
@SteveDunn Thanks!
And additionally it may be great improvement to see one more feature (option) which will simplify using strings. It is "split PascalCase names to words".
So now I have:
```
	[Intellenum<string>]
	[Member("Accounts", "Accounts")]
	[Member("BookDetail", "Book Detail")]
	[Member("BookDetail2", "Book Detail 2")]
	[Member("DailyPL", "Daily PL")]
	[Member("DailyReport", "Daily Report")]
	[Member("FinalSheet", "Final Sheet")]
	[Member("CommissionReport", "Commission Report")]
	public partial class ReportType { }
```
expected:
```
	[Intellenum<string>(Options.SplitToWords)]
	[Members("Accounts, BookDetail, BookDetail2, DailyPL, DailyReport, FinalSheet,  CommissionReport")]
	public partial class ReportType { }
```
