### ISSUE TITLE
Add .NET 8 as target framework

### ISSUE THREAD

**Issue by NoahStolk** [SteveDunn/Intellenum#129]
### Describe the feature

I've been digging around the code base a bit and tried adding .NET 8 in. Builds are succeeding on my branch. Tests are also succeeding except "ScratchSnapshotTests", since it tries to compile using .NET 6 (haven't looked into it yet -- I might be missing something).

I can open a draft PR in case anyone wants to take a look and help out.

**Comment by SteveDunn** [comment]
Hi @NoahStolk - thanks for the feedback. Yes, it should. My time is a bit limited on this project, but I should hopefully be able to get around to it soon.

**Comment by NoahStolk** [comment]
Hi @SteveDunn, no rush. If it helps, I've opened a draft PR with my changes and would be happy to put more time into it to finish it. (Right now I'm not sure what else is needed for this to be fully supported, so I might need some hints.)

But if you'd rather do it yourself, that's fine too. 👍
