### ISSUE TITLE
MemberAttribute-based enums throw NullReferenceException on enumField.Name access

### ISSUE THREAD

**Issue by jupjohn** [SteveDunn/Intellenum#142]
### Describe the bug

When using the `MemberAttribute` way of defining enum values WITHOUT passing a value, accesses to the member's `.Name` field will throw a `NullReferenceException`

### Steps to reproduce

1. Define an Intellenum enum with any backing value type
2. Define a member using the `MemeberAttribute` field *WITHOUT* a value (e.g. `[Member("SomeMember")]`
3. Attempt to access the generated member's `.Name` property 

Outcome: `NullReferenceException` is thrown

Repro code: https://github.com/jupjohn/intellenum-1-0-3-memberattribute-bug

### Expected behaviour

The name should still be accessable, even without a value.

**Comment by jupjohn** [comment]
I'm keen to investigate this one later today, hopefully it's a 2 second fix.

**Comment by jupjohn** [comment]
I can't find any good reason in my test suite as to why `AttributeBasedEnum.One` is null when it's both statically assigned a value in the source generated code, and the rest of the file doesn't differ from the field-backed example. This is super odd... Maybe this ring a bell with you Steve, I'm at a loss so far.

**Comment by SteveDunn** [comment]
Oops! Sorry about that @jupjohn - I'll take a in a moment.

**Comment by SteveDunn** [comment]
Thanks for the repro repo! This issue is that a static constructor is generated and set the `Name` property on the `One` field, but that field hasn't been initialized yet.
```c#
static __Inner()
{
    One.Name = "One";
}
```

But the underlying problem is that it doesn't even _need_ to set it, because it's implied from the attribute and is already generated correctly:

```c#
public static readonly AttributeBasedEnum One = new AttributeBasedEnum("One","One");
```

**Comment by SteveDunn** [comment]
I've fixed that particular problem, but I found another one: if someone does a `public static readonly MyEnum Item1 = new MyEnum()`, then the source generated code should infer the **name** of the enum (`Item1`), and the **value** of the enum (`"Item1"`).
But it doesn't. It does if you specify a value, e.g. `public static readonly MyEnum Item1 = new MyEnum("The item!")`.

I know that inferring the enum name is useful, but I'm wondering if inferring both the name **and** the value is useful...

What do you think?

**Comment by jupjohn** [comment]
Hmm, so if the value isn't inferred it's being defaulted? I'd personally prefer to have it inferred from the name as well - otherwise (based on your example) you have a field that's strongly typed as a `string` but ends up being `null`.

If you were to *not* infer the value, this defaulting behaviour is still potentially problematic and maybe it's worth inserting some predictably generated random value based on the name. Not sure :man_shrugging:

**Comment by SteveDunn** [comment]
I'll think a bit more about this. Having both name and value inferred does lead to some interesting possibilities, e.g.
```c#
class C
{
    public static readonly C One, Two, Three;
}
```
