### ISSUE TITLE
Can't use a record as underlying type without implementing IComparable<T>

### ISSUE THREAD

**Issue by kpietraszko** [SteveDunn/Intellenum#149]
### Describe the bug

When trying to use a simple record as the underlying type for my enum:
```cs
using Intellenum;

public record Size(int Width, int Height, string Unit);

[Intellenum<Size>]
public partial class AllowedSizeEnum
{
    public static readonly AllowedSizeEnum Something = new(new(1, 1, ""));
}
```

I get an error
`Interface member 'int System.IComparable.CompareTo(object?)' is not implemented`

I think there's a bug in the generator, `AllowedSizeEnum` should only need IComparable if its underlying type does.

### Steps to reproduce

See code above

### Expected behaviour

The code example above should build.

**Comment by SteveDunn** [comment]
Thanks for the feedback @kpietraszko . This is now implemented and in release 1.0.5

**Comment by kpietraszko** [comment]
@SteveDunn Thanks! However, it seems that the publish to NuGet failed.

**Comment by SteveDunn** [comment]
Oh no! Thanks for letting me know. I'll look at that shortly!
