### ISSUE TITLE
FromName and other string accepting members should also accept Span

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Intellenum#31]
### Describe the feature

FromName and other string accepting members should also accept Span

**Comment by jupjohn** [comment]
Keen to implement this, just a quick Q.: would you have any issues with the current `(Try)FromName(string)` method's implementation being replaced with a call to the `Span<char>`-accepting implementation via `string.AsSpan()`? Seems like a no-brainer to me, but maybe you'd have a reason not to.

**Comment by SteveDunn** [comment]
I think it'd be a good change to have. Thanks for your help with this, much appreciated!
